jobs:
  - name: get_latest_helm_chart
    type: runSh
    steps:
      # This will automatically set the environment variables needed by rancher-compose
      - IN: pull_release_trigger
      - IN: qingstor_key
      - TASK:
        - script: |
            shippable_retry pip install --upgrade qsctl
            echo "access_key_id: $access_key_id" > config.yaml
            echo "secret_access_key: $secret_access_key" >> config.yaml
            pip install -U qsctl
            mkdir helm
            cd helm
            qstorpath=qs://helm-chart-repo/
            gsutil cp -r gs://kubernetes-charts/* .
            qsctl cp -r --force . $qstorpath -c ../config.yaml --zone pek3a
            cd ..
            rm -rf helm
    on_success:
      - script: echo "Synced helm_chart_repo to bucket"
      - NOTIFY: slack
    on_failure:
      - script: echo "Failed to get latest build $VERSION"
      - NOTIFY: slack
    on_cancel:
      - script: echo "Get latest build $VERSION canceled"
      - NOTIFY: slack
